<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-12-09 16:02
=======
# Generated by Django 3.1.4 on 2020-12-09 16:02
>>>>>>> 5f9caa15e297fff245dba61f1b3b1f3f72a8707e

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
            ],
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_submitted', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Quiz')),
=======
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.quiz')),
>>>>>>> 5f9caa15e297fff245dba61f1b3b1f3f72a8707e
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
<<<<<<< HEAD
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Quiz')),
=======
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.quiz')),
>>>>>>> 5f9caa15e297fff245dba61f1b3b1f3f72a8707e
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Question')),
=======
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.question')),
>>>>>>> 5f9caa15e297fff245dba61f1b3b1f3f72a8707e
            ],
            options={
                'unique_together': {('question', 'choice')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Mark for review'), (2, 'Save & Next')], default=0)),
<<<<<<< HEAD
                ('myAns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizy.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Question')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.QuizRecord')),
=======
                ('myAns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizy.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.question')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.quizrecord')),
>>>>>>> 5f9caa15e297fff245dba61f1b3b1f3f72a8707e
            ],
            options={
                'unique_together': {('record', 'question')},
            },
        ),
    ]
